Fix test collection & fake tensor runtime issues, fix pre-processing for current Transformers version for Groot Model” (#403)
### Ticket
Link to Github Issue - https://github.com/tenstorrent/tt-xla/issues/1891

### Problem description
- Imports were moved inside the **_load_data_config** and **load_model**
methods. This ensures that packages listed in requirements are imported
only when needed, preventing errors during test collection.

### What's changed
- Added necessary device placements to resolve the fake tensor runtime
issue.
- Resolved the AttributeError introduced by the upgrade to [Transformers
v4.57.1](https://github.com/tenstorrent/tt-xla/commit/be941780bfe5141d9b59c99e6072d47fb9cc2837#diff-0b07d5a38e1080a6b2a8dcb43c17dec4107cd0232b0ffad661860e7a9b11db6bL38),
where the
[_prepare_input_image](https://github.com/huggingface/transformers/blob/v4.52.4/src/transformers/image_processing_utils_fast.py#L474)
method is no longer available.
- Updated the implementation to use the corresponding
[_preprocess_image_like_inputs](https://github.com/huggingface/transformers/blob/v4.57.1/src/transformers/image_processing_utils_fast.py#L761)
method to align with the latest Transformers preprocessing workflow.
- Removed and filtered out parameters that are no longer accepted by the
updated _preprocess API to prevent unexpected keyword argument errors.
- Eliminated explicit interpolation parameter conversions, as
interpolation handling is now fully managed by the latest preprocessing
implementation.
- Added required arguments (disable_grouping and expected_ndim) to the
existing preprocessing pipeline to ensure compatibility with the newer
preprocess and
[group_images_by_shape](https://github.com/huggingface/transformers/blob/v4.57.1/src/transformers/image_transforms.py#L845)
methods in the current Transformers version.
### Checklist
- [x] New/Existing tests provide coverage for changes

### Logs
-
[groot_model.log](https://github.com/user-attachments/files/24588511/groot_2.log)