Fix dtype mismatch between model and input in ResNet HF post-processing (#111)
### Ticket

- https://github.com/tenstorrent/tt-forge-fe/issues/2880

### Problem description

- A dtype mismatch occurs between the model and input in ResNet HF
post-processing, resulting in the following error:

```
RuntimeError: Input type (torch.FloatTensor) and weight type (CPUBFloat16Type) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
```

### Root Cause 

- The ResNet HF test
(`forge/test/models/pytorch/vision/resnet/test_resnet.py::test_resnet_hf`)
uses a [new
image](https://github.com/tenstorrent/tt-forge-fe/blob/82d8e73e0a431bf7149370e7a7ff218ac79216fb/forge/test/models/pytorch/vision/resnet/test_resnet.py#L45C5-L46C58)
in post-processing. These images were not converted to the expected
dtype inside run_and_print_results fucntion leading to a mismatch
between the model and input when running tests in bfp16.

### What's changed

- Propagated dtype override information to the relevant post-processing
functions.
- Ensured that inputs are converted to the required dtype within the
function.


### Checklist
- [x] verified the changes with local testing

### Logs

-
[aug25_resnet_after_fix.log](https://github.com/user-attachments/files/21961938/aug25_resnet_af.log)