Add optional dtype conversion for input in deit model (#64)
### Ticket
https://github.com/tenstorrent/tt-forge-fe/issues/2695

### Problem description
Deit model faced below error in tt-forge-fe due to the absence of
optional dtype conversion of input in deit

```
RuntimeError: TT_ASSERT @ /proj_sw/user_dev/kkannan/jul29_bgd25/tt-forge-fe/forge/csrc/passes/dataformat.cpp:98: node->output_df() == default_df_override || node_is_int
E       info:
E       Non integer Input activations should have output_df same as dataformat override which is: Float16_b, but node output_df is: Float32
```

### What's changed
Added optional dtype conversion of input in deit

### Checklist
- [x] New/Existing tests provide coverage for changes