Sparse checkout in non-cone mode (#3797)
### Ticket
slack

### Problem description
Git sparse checkout started causing errors in cone mode with newer git
versions.
The issue is that in newer Git versions, sparse checkout uses "cone
mode", which only accepts directory patterns. Since .gitmodules is a
file (not a directory), it causes the error.

```
/usr/bin/git sparse-checkout set .github/scripts .gitmodules .test_durations pjrt_implementation third_party/pjrt_c_api pytest.ini python_package/requirements.txt integrations/vllm_plugin/requirements-vllm-plugin.txt tests venv examples

 Error: fatal: '.gitmodules' is not a directory; to treat it as a directory anyway, rerun with --skip-checks  
```
To fix this, we disable cone mode by adding sparse-checkout-cone-mode:
false to your checkout configuration

### What's changed
Disable cone mode 

### Checklist
- [ ] New/Existing tests provide coverage for changes