Fix debug mode in flatbuffer_loaded_executable_instance (#1758)
### Problem description
Recent builds are failing with the below error
```
-- Installing: /proj_sw/user_dev/ctr-pmurugan/tt-xla/third_party/tt-mlir/install/include/tt/runtime/types.h
-- Up-to-date: /proj_sw/user_dev/ctr-pmurugan/tt-xla/third_party/tt-mlir/install/include/tt/runtime/utils.h
-- Up-to-date: /proj_sw/user_dev/ctr-pmurugan/tt-xla/third_party/tt-mlir/install/include/tt/runtime/workarounds.h
[240/251] Building CXX object src/common/CMakeFiles/TTPJRTCommon.dir/pjrt_implementation/flatbuffer_loaded_executable_instance.cc.o
FAILED: [code=1] src/common/CMakeFiles/TTPJRTCommon.dir/pjrt_implementation/flatbuffer_loaded_executable_instance.cc.o 
/usr/bin/c++  -I/proj_sw/user_dev/ctr-pmurugan/tt-xla/src -I/proj_sw/user_dev/ctr-pmurugan/tt-xla/inc -I/proj_sw/user_dev/ctr-pmurugan/tt-xla/third_party/loguru/src/loguru-install/include -I/proj_sw/user_dev/ctr-pmurugan/tt-xla/third_party/pjrt_c_api -I/proj_sw/user_dev/ctr-pmurugan/tt-xla/third_party/tt-mlir/install/include -I/opt/ttmlir-toolchain/include -I/opt/ttmlir-toolchain/src/shardy -I/opt/ttmlir-toolchain/src/stablehlo -I/proj_sw/user_dev/ctr-pmurugan/tt-xla/build/_deps/protobuf-src/src -fno-rtti -std=gnu++17 -fPIC -MD -MT src/common/CMakeFiles/TTPJRTCommon.dir/pjrt_implementation/flatbuffer_loaded_executable_instance.cc.o -MF src/common/CMakeFiles/TTPJRTCommon.dir/pjrt_implementation/flatbuffer_loaded_executable_instance.cc.o.d -o src/common/CMakeFiles/TTPJRTCommon.dir/pjrt_implementation/flatbuffer_loaded_executable_instance.cc.o -c /proj_sw/user_dev/ctr-pmurugan/tt-xla/src/common/pjrt_implementation/flatbuffer_loaded_executable_instance.cc
In file included from /proj_sw/user_dev/ctr-pmurugan/tt-xla/src/common/status.h:9,
                 from /proj_sw/user_dev/ctr-pmurugan/tt-xla/inc/common/pjrt_implementation/module_builder/module_builder.h:36,
                 from /proj_sw/user_dev/ctr-pmurugan/tt-xla/inc/common/pjrt_implementation/executable_image.h:30,
                 from /proj_sw/user_dev/ctr-pmurugan/tt-xla/inc/common/pjrt_implementation/loaded_executable_instance.h:24,
                 from /proj_sw/user_dev/ctr-pmurugan/tt-xla/inc/common/pjrt_implementation/flatbuffer_loaded_executable_instance.h:25,
                 from /proj_sw/user_dev/ctr-pmurugan/tt-xla/src/common/pjrt_implementation/flatbuffer_loaded_executable_instance.cc:6:
/proj_sw/user_dev/ctr-pmurugan/tt-xla/src/common/pjrt_implementation/flatbuffer_loaded_executable_instance.cc: In member function ‘void tt::pjrt::FlatbufferLoadedExecutableInstance::dumpInputs(const std::vector<tt::runtime::Tensor>&)’:
/proj_sw/user_dev/ctr-pmurugan/tt-xla/src/common/pjrt_implementation/flatbuffer_loaded_executable_instance.cc:507:3: error: ‘Verbosity_DEBUG’ is not a member of ‘loguru’; did you mean ‘Verbosity_OFF’?
  507 |   DLOG_F(DEBUG, "FlatbufferLoadedExecutableInstance::dumpInputs");
      |   ^~~~~~
/proj_sw/user_dev/ctr-pmurugan/tt-xla/src/common/pjrt_implementation/flatbuffer_loaded_executable_instance.cc:507:3: error: ‘Verbosity_DEBUG’ is not a member of ‘loguru’; did you mean ‘Verbosity_OFF’?
  507 |   DLOG_F(DEBUG, "FlatbufferLoadedExecutableInstance::dumpInputs");
      |   ^~~~~~
[247/251] Building CXX object src/common/CMakeFiles/TTPJRTCommon.dir/pjrt_implementation/module_builder/module_builder.cc.o
ninja: build stopped: subcommand failed.
```
In loguru, there is no DEBUG mode. It must be a typo added in recent
[PR](https://github.com/tenstorrent/tt-xla/pull/1612)

### What's changed
`DEBUG` is replaced with `LOG_DEBUG` which is already used in
multiple_places.