Fix einsum override for linear functions (#2412)
### Ticket
https://github.com/tenstorrent/tt-xla/issues/2407

### Problem description
Swin fails on [latest perf benchmark
nightly](https://github.com/tenstorrent/tt-forge/actions/runs/19847809624/job/56868529851)
with error:
```
res = torch.einsum("...mk,...kn->...mn", args[0], args[1])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/functional.py", line 422, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: einsum(): subscript k has size 384 for operand 1 which does not broadcast with previously seen size 96
```

We see this issue because [linear functions transpose the
weight](https://docs.pytorch.org/docs/stable/generated/torch.nn.functional.linear.html)
before computing a regular matmul, so for `func.__name__ == "linear"`
the einsum equation should be `"...mk,...nk->...mn"` ([n, k]) instead of
`"...mk,...kn->...mn"` ([k, n]).

### What's changed
- Changed the einsum equation in `TorchFunctionOverride` to be
`"...mk,...nk->...mn"` when `func.__name__ == "linear"`.
- Added a linear_torch_override unit test to replicate the conditions
that caused a failure in swin and ensure the correct einsum equation is
used for linear functions.

### Checklist
- [x] New/Existing tests provide coverage for changes