Update config files (#3851)
Update test configs for tests:

- gpt_oss/pytorch-20B-tensor_parallel-inference
```
PCC comparison failed. Calculated: pcc=0.9797330843468324. Required: pcc=0.98.
```
- maskformer_swin_b/pytorch-Swin_Base_Coco-single_device-inference
```
Error: The action 'Run tests' has timed out after 240 minutes.
```
- falcon/pytorch-3_7B_Base-tensor_parallel-training
```
TT_FATAL: Buffer must be allocated on device! (assert.hpp:104)
terminate called after throwing an instance of 'std::runtime_error'
Fatal Python error: Aborted
```