Fix Torch Dynamo Failure in VADv2 and SSR Model (#398)
### Ticket

Fixes[ #2755](https://github.com/tenstorrent/tt-xla/issues/2755) and
[#2756](https://github.com/tenstorrent/tt-xla/issues/2756)

### Problem description
VADv2 model fails with below error:

```
torch._dynamo.exc.TorchRuntimeError: Dynamo failed to run FX node with fake tensors: call_function <Wrapped method <original pow>>(*(FakeTensor(..., size=(1,)), 2), **{}): got AttributeError("'ndarray' object has no attribute 'pow'")
```
and SSR Model fails with 

```
torch._dynamo.exc.TorchRuntimeError: Dynamo failed to run FX node with fake tensors: call_function <Wrapped method <original div>>(*(FakeTensor(..., size=(), dtype=torch.float64), 3.141592653589793), **{}): got AttributeError("'ndarray' object has no attribute 'div'")
```

### What's changed

- Made modifications in get_bev_features function to replace all numpy
ops with torch ops with right device and dtype. All numpy math has been
converted to torch math to get rid of the attribute error. Following
this, model failed with numpy related attribute errors from various
parts of models, all these parts were converted to equivalent torch ops.
After all changes, model was tested to verify that there is no deviation
in final results from original results. Post these changes, model was
failing with out of memory error. SSR Model was fixed by converting
problematic areas causing attribute errors to entirely torch ops which
was failing with out of memory as well finally.

### Log

[vadv2.log](https://github.com/user-attachments/files/24580209/vadv2_eval_single_col_final_oom.log)

[ssr.log](https://github.com/user-attachments/files/24580213/ssr_oom.log)