Fix RuntimeError: Wrong input shape Expected input H,W divisible by 32. (#133)
### Ticket
 [Issue](https://github.com/tenstorrent/tt-forge-fe/issues/2920)

### Problem description
RuntimeError: Wrong input shape height=1213, width=1546. Expected image
height and width divisible by 32.

### What's changed
The loader.py of the unet script is changed where the load_input
function is modified

### Model Log 
**Before Fix**

[unet_qubvel_pytorch_before_fix.log](https://github.com/user-attachments/files/22088318/unet_qubvel_pytorch.log)
**After Fix** 

[unet_model_qubvel_after_fix.log](https://github.com/user-attachments/files/22134962/unet_model_qubvel_after_fix.log)