Warn when relocating venv instead of silently breaking (#4231)
### Ticket
Discovered while testing #4320

### Problem description

Python venvs are not relocatable and will silently fail if you try to
relocate them.

When running `source venv/activate` for the first time, we use python's
venv module via `python3.12 -m venv $TTMLIR_VENV_DIR` to create a venv
inside the workspace.

Part of the python venv creation involves generating the
`venv/bin/activate` script, which exports VIRTUAL_ENV to the hardcoded
path to the venv _at the time of venv creation_. Eg.

`export VIRTUAL_ENV=/localdev/jameszianxu/scratch/tt-xla/venv`

Multihost CI integration will involve creating a sibling container in
the same host and in the main `container:` where the venv is initially
created, the absolute path to the venv is baked into the
`venv/bin/activate` script.

When the sibling container spins up, it may have a different absolute
path within its container to the venv, even though the relative path to
the github workspace will remain the same from the CI execution
environment (eg. inside _work/tt-xla/tt-xla). So, when running
`venv/activate` from a sibling container, the VIRTUAL_ENV will be
pointing to a different and nonexistent path, leading to failures in
locating python and installed modules.

### What's changed
Add an additional check comparing VIRTUAL_ENV (set by venv module in
venv/bin/activate script at venv creation time to hardcoded path) and
TTMLIR_VENV_DIR, which is the actual path to the venv from the
perspective of the venv/activate user.

If these differ, aggressively warn. 

This was really a pain to discover and debug so the point of this PR is
to explicitly block such mistakes in the future.

### Local Testing
```bash
$ mv venv tmp/venv
$ cd tmp/

# before - nothing, but python3 would point to user python and see user libs
# even though the venv install was intact, just at a different abs path
# relative to the first time it was created
$ source venv/activate 

# after - loudly warn
$ source venv/activate 
ERROR: detected relocated Python virtualenv.
Expected: /localdev/jameszianxu/scratch/tt-xla/tmp/venv
Actual:   /localdev/jameszianxu/scratch/tt-xla/venv
This venv was created at a different absolute path and is not safe to reuse.
Please remove '/localdev/jameszianxu/scratch/tt-xla/tmp/venv' and recreate it from this workspace path.
```