Add test config for unet_480x640 variant and change the failure reason for phi3.5-vision (#2245)
### Ticket

- https://github.com/tenstorrent/tt-xla/issues/2111
- https://github.com/tenstorrent/tt-xla/issues/1865

### Problem description

- Add inference test config for 480x640 vanilla unet variant 
- `TypeError: Phi3VForCausalLM.forward() got
an unexpected keyword argument 'max_new_tokens'` fixed by this
[tt-forge-models
PR](https://github.com/tenstorrent/tt-forge-models/pull/283). So update
the reason with current failure

### What's changed

- Added test config for 480x640 vanilla variant and updated the failure
reason for phi3.5-vision

### Checklist
- [x] Verified the changes through local testing

### Logs

-
[nov20_carvana_unet_480x640_xla.log](https://github.com/user-attachments/files/23647872/nov20_carvana_unet_480x640_xla.log)
-
[nov20_phi_3_5_vision_xla.log](https://github.com/user-attachments/files/23647874/nov20_phi_3_5_vision_xla.log)