Fix Torch Dynamo Failure in BEVFormer and Maptr (#341)
### Ticket
Fixes [#2532](https://github.com/tenstorrent/tt-xla/issues/2532)

### Problem description

Following variants of BEVFormer and Maptr fail with`
torch._dynamo.exc.TorchRuntimeError: Dynamo failed to run FX node with
fake tensors: call_function <Wrapped method <original
div>>(*(FakeTensor(..., size=(), dtype=torch.float64),
3.141592653589793), **{}): got AttributeError("'ndarray' object has no
attribute 'div'")` error:

- bevformer/pytorch-BEVFormer-base-single_device-full-inference

- bevformer/pytorch-BEVFormer-small-single_device-full-inference

- bevformer/pytorch-BEVFormer-tiny-single_device-full-inference

- maptr/pytorch-tiny_r50_24e_bevformer-single_device-full-inference

- maptr/pytorch-tiny_r50_110e-single_device-full-inference

### What's changed
This error arises from mixing NumPy arrays with Torch math during
TorchDynamo tracing.During tracing, with FakeTensors, it tries to lower
ops like division/subtraction using tensor methods, so when numpy nd
array is traced, there’s no .div method, so this hits the
AttributeError("'ndarray' object has no attribute 'div'").Hence a single
torch tensor has been built and numpy operations have been replaced with
equivalent torch operations to fix this issue.No deviation in model
outputs is noticed post these changes. After these changes, bevformer
model fails with Bad status access error while maptr fails with Out of
Memory Error.

### Logs

[bevformer_before_fix.log](https://github.com/user-attachments/files/24156633/bevformer_xla_before.log)

[bevformer_post_fix.log](https://github.com/user-attachments/files/24344870/bevformer_post_fix.log)


[maptr_before_fix.log](https://github.com/user-attachments/files/24344877/maptr_before_fix.log)

[maptr_post_fix.log](https://github.com/user-attachments/files/24344890/maptr_post_fix.log)