Add custom test for Surya OCR model (#1970)
### Ticket
Fixes [#243 ](https://github.com/tenstorrent/tt-forge-models/issues/243)

### Problem description and changes

-  Model fails with below error from torch dynamo

```
            try:
                value.flags.writeable = True
            except ValueError:
                # One can not easily make nditer elements writable,
                # but warning is not the end of the world
>               assert isinstance(value.base, np.nditer)
E               AssertionError: 
E               
E               from user code:
E                  File "tt-xla/venv/lib/python3.11/site-packages/surya/detection/__init__.py", line 59, in torch_dynamo_resume_in_prepare_image_at_59
E                   img = np.asarray(img, dtype=np.uint8)

venv/lib/python3.11/site-packages/torch/_dynamo/variables/builder.py:1887: AssertionError
```

- The failure came from using np.asarray on a PIL Image, which can
return a non-writeable view backed by PIL’s memory. TorchDynamo then
tries to toggle writeable and hits an internal assertion. Switching to
np.array(..., copy=True) forces a fresh, contiguous, writeable NumPy
buffer (no odd base, flags.writeable=True). This change has been brought
in by monkey-patching this change.

- Custom test has been created to accomodate the above mentioned changes
and model fails with `E torch._dynamo.exc.TorchRuntimeError: Dynamo
failed to run FX node with fake tensors: call_function <Wrapped method
<original mul>>(*(FakeTensor(..., size=(1200, 1200, 3),
dtype=torch.float64), 0.00392156862745098), **{}): got
AttributeError("'ndarray' object has no attribute 'mul'")
`

- This failure is added as xfail in the inference test and will be
handled in a future PR.

### Logs

[surya_ocr_text_xla.log](https://github.com/user-attachments/files/24100096/surya_ocr_text_xla.log)