Fix torch_function_override nightly errors (#2452)
### Ticket
https://github.com/tenstorrent/tt-xla/issues/2396

### Problem description
The use of TorchFunctionOverride is causing the following errors in
nightly tests.
**Tensor attribute access error:**
```
TypeError: arange() received an invalid combination of arguments - got (int, int, device=torch.Size, dtype=torch.dtype), but expected one of:
E            * (Number end, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
E            * (Number start, Number end, *, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
E            * (Number start, Number end, Number step = 1, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
```
This caused by calling `torch.compiler.is_compiling()` for every
function that passes through `__torch__function__`. It causes tensor
attributes accesses to always return the value of the first attribute
accessed.
 
[EDIT]: transfuser is failing with a new torch override related error
after rebasing, so it will be fixed in a seperate pr.

### What's changed
The **tensor attribute error** is resolved when we only call
`torch.compiler.is_compiling()` if the function is linear or matmul:
```
if (
     func.__name__ == "matmul" or func.__name__ == "linear"
) and not torch.compiler.is_compiling():
```
Added a unit test `test_tensor_attributes_torch_override` that is now
passing with the above change.

### Checklist
- [x] New/Existing tests provide coverage for changes