Fixed MapTR, Bevformer, SSR, VADv2 models with  no attribute 'xla_args' errors (#493)
### Ticket
closes https://github.com/tenstorrent/tt-xla/issues/3314

### Problem description
MapTR(except fusion variant) , Bevformer, SSR, VADv2 variants facing
below issue
`AttributeError: 'fused_0' object has no attribute 'xla_args'`


### What's changed
Converted can_bus variable from numpy to a tensor on the model's device
so that the compiled graph fragment for simple_test receives a properly
placed tensor instead of a CPU tensor (which breaks XLA graph
partitioning).